### ISSUE TITLE
'./data/questions/SynHOTS-VQA_proc_train.json'

### ISSUE THREAD

**Issue by zbj165** [gtziafas/ns-man#1]
Hi，Where do I get './data/questions/SynHOTS-VQA_proc_train.json'and'./data/questions/SynHOTS-VQA_proc_val.json'

**Comment by zbj165** [comment]
Any plans to update the readme?

**Comment by gtziafas** [comment]
Hi @zbj165, this codebase is actually deprecated, I should remove the link in the project's webpage [webpage](https://gtziafas.github.io/neurosymbolic-manipulation/). About the dataset, it will be released after submission decision of that work. Check the link for progress if interested.

**Comment by zbj165** [comment]
> Hi @zbj165, this codebase is actually deprecated, I should remove the link in the project's webpage [webpage](https://gtziafas.github.io/neurosymbolic-manipulation/). About the dataset, it will be released after submission decision of that work. Check the link for progress if interested.

@gtziafas Oh, that's really sad news! Will the code be re-uploaded in the future?
